version: "3.6" ## especifica a versão do docker-compose file

services: ## Define um serviço
  server: ## nome do serviço
    image: node:16-alpine
    user: root
    working_dir: /usr/app/server
    restart: always
    command: > 
      sh -c "npm install && npx sequelize-cli db:migrate && 
             npx sequelize-cli db:seed:undo:all && 
             npx sequelize-cli db:seed:all && 
             npx nodemon index.js" ## comando a executar
    ports:
      - "3001:3001" ## redirecionamento de porta quando chegar alguma requisição na porta 5001 chama o container na porta 3001
    volumes:
      - ./server:/usr/app/server ## monitoro a pasta atual . e envio as alterações
  app: ## nome do serviço  
    image: node:16-alpine
    restart: always
    working_dir: /usr/app
    command: > 
      sh -c "npm install && npm start" ## comando a executar
    ports:
      - "3000:3000" ## redirecionamento de porta quando chegar alguma requisição na porta 5000 chama o container na porta 3000
    volumes:
      - .:/usr/app ## monitoro a pasta atual . e envio as alterações para /usr/app

    ## entrar no continer
    ## sudo docker exec -it [idcontainer] /bin/sh